apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-bot
  labels:
    app: k8s-bot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-bot
  template:
    metadata:
      labels:
        app: k8s-bot
    spec:
      containers:
        - name: k8s-bot
          image: ashwanth01/k8s-bot:latest   # 👈 gets patched by CI
          imagePullPolicy: Always
          ports:
            - containerPort: 5000
          env:
            - name: AWS_ACCESS_KEY_ID
              valueFrom:
                secretKeyRef:
                  name: k8s-bot-secrets
                  key: aws-access-key-id
            - name: AWS_SECRET_ACCESS_KEY
              valueFrom:
                secretKeyRef:
                  name: k8s-bot-secrets
                  key: aws-secret-access-key
            - name: AWS_DEFAULT_REGION
              value: "us-east-1"
            - name: SECRET_KEY
              valueFrom:
                secretKeyRef:
                  name: k8s-bot-secrets
                  key: flask-secret-key

