name: kubester

on:
  workflow_dispatch:

jobs:
  kubester-build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ashwanth01/k8s-bot:latest -t ashwanth01/k8s-bot:${{ github.sha }} .
        
    - name: Create k8s-bot-secrets secret
      run: |
        kubectl delete secret k8s-bot-secrets --ignore-not-found
        kubectl create secret generic k8s-bot-secrets \
          --from-literal=aws-access-key-id="${{ secrets.AWS_ACCESS_KEY_ID }}" \
          --from-literal=aws-secret-access-key="${{ secrets.AWS_SECRET_ACCESS_KEY }}" \
          --from-literal=flask-secret-key="secrets.FLASK_KEY" \
          --from-literal=aws-region="${{ secrets.AWS_REGION }}"

    - name: Push Docker image
      run: |
        docker push ashwanth01/k8s-bot:latest
        docker push ashwanth01/k8s-bot:${{ github.sha }}

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Update Deployment with GitHub SHA image
      run: |
        kubectl set image deployment/k8s-bot \
          k8s-bot=ashwanth01/k8s-bot:${{ github.sha }} --record

    - name: Show running port
      run: echo "✅ Application is running on port 30001"

