name: kubester

on:
  workflow_dispatch:

jobs:
  kubester-build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ashwanth01/k8s-bot:latest
          ashwanth01/k8s-bot:${{ github.sha }}

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Update image in Deployment
      run: |
        kubectl set image deployment/k8s-bot \
          k8s-bot=ashwanth01/k8s-bot:${{ github.sha }} --record

    - name: Get Service NodePort URL
      id: service-url
      run: |
        NODE_IP=$(hostname -I | awk '{print $1}')
        echo "NODE_IP=$NODE_IP" >> $GITHUB_ENV
        echo "App running at: http://$NODE_IP:30080"

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/k8s-bot
        kubectl get pods -l app=k8s-bot

    - name: Test application
      run: |
        sleep 30
        curl -f http://$NODE_IP:30080 || exit 1

    - name: Cleanup on failure
      if: failure()
      run: |
        kubectl delete deployment k8s-bot --ignore-not-found
        kubectl delete service k8s-bot --ignore-not-found
