name: kubester

on:
  workflow_dispatch:

jobs:
  kubester-build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      run: |
        echo "${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}" | docker login -u "${{ secrets.DOCKER_HUB_USERNAME }}" --password-stdin

    - name: Build Docker image
      run: |
        docker build -t ashwanth01/k8s-bot:latest -t ashwanth01/k8s-bot:${{ github.sha }} .

    - name: Push Docker image
      run: |
        docker push ashwanth01/k8s-bot:latest
        docker push ashwanth01/k8s-bot:${{ github.sha }}

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Update Deployment with GitHub SHA image
      run: |
        kubectl set image deployment/k8s-bot \
          k8s-bot=ashwanth01/k8s-bot:${{ github.sha }} --record
