name: Build & Deploy to K8s

on:
  workflow_dispatch:   
jobs:
  build-and-deploy:
    runs-on: self-hosted

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log in to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKER_HUB_USERNAME }}
        password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}

    - name: Build and push Docker image
      uses: docker/build-push-action@v4
      with:
        context: .
        push: true
        tags: |
          ashwanth01/ashapp-backend:latest
          ashwanth01/ashapp-backend:${{ github.sha }}

    - name: Apply Kubernetes manifests
      run: |
        kubectl apply -f k8s/deployment.yaml
        kubectl apply -f k8s/service.yaml

    - name: Get Service NodePort URL
      id: service-url
      run: |
        NODE_IP=$(hostname -I | awk '{print $1}')
        echo "NODE_IP=$NODE_IP" >> $GITHUB_ENV
        echo "App running at: http://$NODE_IP:30080"

    - name: Verify deployment
      run: |
        kubectl rollout status deployment/ashapp-backend
        kubectl get pods -l app=ashapp-backend

    - name: Test application
      run: |
        sleep 30
        curl -f http://$NODE_IP:30080 || exit 1

    - name: Cleanup on failure
      if: failure()
      run: |
        kubectl delete deployment ashapp-backend --ignore-not-found
        kubectl delete service ashapp-backend --ignore-not-found
